spring:
  datasource:
    url: "jdbc:mysql://mydb.cd2ixijusx48.ap-northeast-2.rds.amazonaws.com:3306/library"
    username: "admin"
    password: "!dmssk6480"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect